sudo: required
language: python
python:
  - 2.7
install:
  - pip install flake8
  - pip install yapf==0.26.0

services:
  - docker
  - git

git:
  depth: 1

jobs:
  include:
    - stage: check
      script: ./check_code.sh || travis_terminate 1;
    - stage: build
      script:
        - ./travis_build.sh || travis_terminate 1;
