{{- if .Values.adaptor.enable }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.adaptor.fullname }}
  labels:
    rainbond: adaptor
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    rainbond: adaptor
{{- end }}
