{{- if .Values.allinone.enable }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.allinone.fullname }}
  labels:
    rainbond: allinone
spec:
  type: {{ .Values.allinone.svc.type }}
  selector:
    rainbond: allinone
  ports:
    - port: 7070
      targetPort: 7070
      {{ if eq .Values.allinone.svc.type "NodePort" }}
      nodePort: {{ .Values.allinone.svc.nodePort }}
      {{ end }}
{{- end }}