{{- if .Values.allinone.enable }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.allinone.fullname }}-pvc-data
spec:
  storageClassName: {{ .Values.pvc.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.storageSize }}
{{- end }}
---

{{- if .Values.allinone.enable }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.allinone.fullname }}-pvc-ssh
spec:
  storageClassName: {{ .Values.pvc.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.storageSize }}
{{- end }}