{{- if .Values.console.enable }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.console.fullname }}
  labels:
    rainbond: console
spec:
  ports:
  - port: 5000
    protocol: TCP
  selector:
    rainbond: console
{{- end }}