name: pr-ci-build

on:
  pull_request:
    branches: [master, V5.3]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip3 install --upgrade pip
          pip3 install flake8 yapf==0.26.0

      - name: check-code
        run: ./check_code.sh

      - name: Build the Docker image
        env:
          TRAVIS_PULL_REQUEST: true
        run: VERSION=${{ github.base_ref }}-dev ./release.sh
